import type { Metadata } from "next";
import { Roboto_Mono as RobotoMonoFont } from "next/font/google";
import "../app/globals.css";
import AuthProvider from "../../(component)/AuthProvider";

// Use the renamed constant
const robotoMono = RobotoMonoFont({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      {/* Apply the robotoMono.className here */}
      <body className={`${robotoMono.className} antialiased`}>
       {children}
      </body>
      </AuthProvider>
    </html>
  );
}
